In [22]:
import numpy as np

# qr正交分解
A = np.matrix("9 0 -1 2; -5 7 -9 5; 2 5 6 -3")
# help(np.linalg.qr)
# np.linalg.qr()
q, r = np.linalg.qr(A)
print(q)
print(r)

# 特征值&特征向量 Ax = ℷx

# 空间五点共面分析
# （1）是一个平面吗，用秩判断
A = np.matrix('''-0.28, 4, 0.72, 2.70, 2.0;
              -0.03, 4.60,0.71,4.20,1.80;
              0.55, 3, -0.13, 6.20,-0.32''')
# B = A - A(:5)  
print(A.item(4))



[[-0.85811633 -0.2474695  -0.44988355]
 [ 0.47673129 -0.70941257 -0.51909641]
 [-0.19069252 -0.65991867  0.72673497]]
[[-10.48808848   2.38365647  -4.57662043   1.23950137]
 [  0.          -8.26548134   2.67267061  -2.06224584]
 [  0.           0.           9.482161    -5.67545403]]
2.0


In [46]:
import numpy as np
# numpy help us do some vector calculation


class Point(object):
    """Point are two-dimension"""

    def __init__(self, x, y):
        self.x = x
        self.y = y


class Segment(object):
    """the 2 points p1 and p2 are unordered"""

    def __init__(self, p1, p2):
        self.p1 = p1
        self.p2 = p2


class Line(object):
    """p1 and p2 are 2 points in straight line"""

    def __init__(self, p1, p2):
        self.p1 = p1
        self.p2 = p2


class Vector(object):
    """start and end are two points"""

    def __init__(self, start, end):
        self.x = end.x - start.x
        self.y = end.y - start.y
def pointDistance(p1, p2):
    """calculate the distance between point p1 and p2"""

    # v: a Vector object
    v = Vector(p1, p2)

    # translate v to a ndarray object
    t = np.array([v.x, v.y])

    # calculate the inner product of ndarray t
    return float(np.sqrt(t @ t))


def pointToLine(C, AB):
    """calculate the shortest distance between point C and straight line AB, return: a float value"""

    # two Vector object
    vector_AB = Vector(AB.p1, AB.p2)
    vector_AC = Vector(AB.p1, C)

    # two ndarray object
    tAB = np.array([vector_AB.x, vector_AB.y])
    tAC = np.array([vector_AC.x, vector_AC.y])

    # vector AD, type: ndarray
    tAD = ((tAB @ tAC) / (tAB @ tAB)) * tAB

    # get point D
    Dx, Dy = tAD[0] + AB.p1.x, tAD[1] + AB.p1.y
    D = Point(Dx, Dy)

    return pointDistance(D, C)


a = Point(1, 0)
b = Point(1.5, 0.7)
c = Point(3, 2.7)
d = Point(3.5, 3.5)
e = Point(4.5, 5)

ae = Line(a, e)

print(pointToLine(b, ae))
print(pointToLine(c, ae))
print(pointToLine(d, ae))





0.008192319205190503
0.09011551125709442
0.04096159602595202
