In [37]:
import numpy as np
print(np.__version__)
# dir(np)
# aa = np.arange(10) 
# print(aa)
# print(type(aa))
a1 = np.arange(1, 13)
a2 = np.arange(13, 25)
# print(aa, bb)
# help(np.concatenate)
a = np.concatenate((a1, a2))
print(a)
# help(np.hsplit)
# hh = np.hsplit(a, (2,4,6,25))
# print(hh)
# help(np.split)
# ss = np.split(a, [2], 0)
# print(ss)

bb = a.reshape(2,2,2,3)
# print(bb)
# dd = np.hsplit(bb, 2)
# print(dd)
# help(np.vsplit)
# ee = np.vsplit(a, 2)
# print(ee)
# help(np.hsplit)
# # aa = np.split(a, 2, axis=0)
# aa = np.hsplit(a,2)
# print(aa)
print(bb)


1.12.1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]
